### ISSUE TITLE
No test runner in your project. Please install one.

### ISSUE THREAD

**Issue by felixjb** [felixjb/testify#15]
**Describe the bug**
Sometimes the extension can't find the test runner in the project. Usually it happens when VSCode is not opened through the project's directory.

**To Reproduce**
1. Click on the "Run test" codelens
2. See a snack bar with the error pop up to the right

**Expected behavior**
It should find the installed and adequate test runner for the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/16679401/61100876-16dcaf80-a43e-11e9-9358-66e2202578e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, Ubuntu 18.04
 - Version 1.1.0

**Additional context**
This [issue](https://github.com/g3offrey/javascript-test-runner/issues/29) was first opened at the original repo.

**Comment by TyAssis** [comment]
I had the same problem on Ubuntu 18

**Comment by felixjb** [comment]
I'm sorry about that! I'm going to make this top priority right now for the project.

**Comment by felixjb** [comment]
After talking to @villasv I realized that this is more of a feature request than a bug, as it is expected by the VSCode to find `node_modules` in the root directory of the project.
Anyway, this will be top priority now, but I'll be working on it from the issue #9

**Comment by villasv** [comment]
I said that the issue @TyAssis was facing was a feature request. The original issue is caused by Windows and is an actual bug.

[But wasn't the orignal issue solved?](https://github.com/g3offrey/javascript-test-runner/issues/29#issuecomment-522827251)

**Comment by felixjb** [comment]
The issue on Windows was solved, indeed.

Now we only have to work on specifying the test runner path.

**Comment by ranger2255** [comment]
Facing a similar issue with mac; added the test runner path in setting, still the same error pops up
<img width="1086" alt="Screenshot 2024-10-25 at 8 47 15 AM" src="https://github.com/user-attachments/assets/16e84ceb-3650-47d0-a544-a8e704287adf">

**Comment by felixjb** [comment]
Hello @ranger2255 

I think you should use the path from executable in the node_modules in the repository you are working on.
